name: Scan Docker Image
on: [push]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: xavitu94/example-voting-app-main/example-voting-app-main/result/dockerfile:latest

    - name: Scan the image using sysdig-cli-scanner
      env:
        SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
      run: |
        docker pull xavitu94/example-voting-app-main/example-voting-app-main/result/dockerfile:latest
        docker save xavitu94/example-voting-app-main/example-voting-app-main/result/dockerfile:latest | docker run --rm -i -v /var/run/docker.sock:/var/run/docker.sock quay.io/sysdig/secure-inline-scan:2 --sysdig-url https://secure.sysdig.com --sysdig-token ${{ secrets.SECURE_API_TOKEN }} --storage-type docker-daemon --storage-path /var/run/docker.sock -
