name: Sysdig Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sysdig_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sysdig Secure Inline Scan
      uses: sysdiglabs/scan-action@v3.5.0
      with:
        image-tag: "dockersamples/example-voting-app:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
