   name: Sysdig Scan

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
     sysdig_scan:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2
         
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         
       - name: Sysdig Scan
         run: |
           docker pull dockersamples/example-voting-app:latest
           docker save dockersamples/example-voting-app:latest | sysdig --docker-timeout 300 scan --force

       - name: Save Sysdig Scan Results
         run: |
           docker pull dockersamples/example-voting-app:latest
           docker save dockersamples/example-voting-app:latest | sysdig --docker-timeout 300 scan --force -o sysdig_scan_results.json

       - name: Upload Sysdig Scan Results
         uses: actions/upload-artifact@v2
         with:
           name: sysdig-scan-results
           path: sysdig_scan_results.json



