name: Container build, scan and push

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
