name: Container build, scan and push

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build container image
      run: |
          docker build -t my-image:${{ github.sha }} -f ./example-voting-app-main/example-voting-app-main/Dockerfile ./example-voting-app-main/example-voting-app-main
