
env:
    SYSDIG_SECURE_ENDPOINT: "https://eu1.app.sysdig.com"
    REGISTRY_HOST: "docker.io"
    IMAGE_NAME: "voteapp"
    IMAGE_TAG: "latest"
    DOCKERFILE_CONTEXT: "example-voting-app-main/example-voting-app-main/vote"

name: Container build, scan and push

on: [push, pull_request]

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
       
    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: cache
        key: ${{ runner.os }}-cache-${{ hashFiles('**/sysdig-cli-scanner', '**/latest_version.txt', '**/db/main.db.meta.json', '**/scanner-cache/inlineScannerCache.db') }}
        restore-keys: ${{ runner.os }}-cache-

    - name: Scan image
      id: scan
      uses: sysdiglabs/scan-action@v5
      with:
          sysdig-secure-url: https://eu1.app.sysdig.com
          image-tag: "sysdiglabs/dummy-vuln-app:latest"
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
